### PR TITLE
Add CONN_HEALTH_CHECKS to _DB_BASE_OPTIONS

### PR DESCRIPTION
**Pull request by denys-pidlisnyi**
https://docs.djangoproject.com/en/4.1/ref/settings/#conn-health-checks

### CODE REVIEW

**Comment by denys-pidlisnyi** [comment]
https://github.com/joke2k/django-environ/issues/413

**Comment by denys-pidlisnyi** [comment]
@sergeyklay

**Comment by sergeyklay** [comment]
@denys-pidlisnyi Could you please send this PR to develop branch?

**Comment by denys-pidlisnyi** [comment]
@sergeyklay Done

**Review by sergeyklay — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
