### PR TITLE
Keep newline/tab escapes in quoted strings (fix certificate serializing)

### PR DESCRIPTION
**Pull request by johnbergvall**
Change parsing of quoted strings to not remove \ before \r, \n and \t to allow basic formatting and certificate serializing.

Also include optional \r in delimiter when splitting string to multiple lines for better compatibility with PEM-certificates and MIME-headers

Example certificate data
`VAR="---BEGIN---\r\n---END---"`
now becomes
`r"---BEGIN---\r\n---END---"`
instead of
`r"---BEGIN---rn---END---"`

This makes linebreaks work correctly with Env().str('VAR', multiline=True) as well

### CODE REVIEW

**Comment by sergeyklay** [comment]
Implemented in my fork sergeyklay/django-environ-2#29

**Comment by sergeyklay** [comment]
PR was closed by mistake. Reopened it.

**Comment by johnbergvall** [comment]
I've rebased this onto the latest `develop` and included your changes from sergeyklay/django-environ-2#29

**Comment by sergeyklay** [comment]
I'll review this PR ASAP. Thank you for the contributing!

**Review by sergeyklay — APPROVED** [review]
Looks good to me

**Comment by sergeyklay** [comment]
Merged! Thank you for the patch, and for helping us make django-environ better.

**Pull request merged**
