### PR TITLE
♻️Refactor the README and tox.ini 

### PR DESCRIPTION
**Pull request by simkimsia**
to correct a typo in README
and to make the tox.ini consistent by dropping the rc1 for Django 4.2

related to #456

### CODE REVIEW

**Comment by joke2k** [comment]
Hi @simkimsia, thank you for your PR.

It resolves the #473 as well, right?

**Comment by simkimsia** [comment]
@joke2k 

Yes 

two birds 🐦 one stone 🗿

🙌

**Comment by simkimsia** [comment]
Sorry just asking, @joke2k any estimate on when you will release a new version that's Django 4.2 compatible on pypi?

**Comment by sergeyklay** [comment]
@simkimsia We'll release new version ASAP.

**Pull request merged**
