### PR TITLE
Option to override existing variables with read_env

### LINKED ISSUE #249: Won't update environ key if it already set
imagine a case when we need to update some of the production settings in `production.py` base on `base.py`.

```py
from .base import *

environ.Env.read_env(env_file="/etc/<app>/.env")

DATABASES = {
    # read os.environ['DATABASE_URL'] and raises ImproperlyConfigured exception if not found
    "default": env.db(),
}

CELERY_BROKER_URL = env("REDIS_URL")
CELERY_RESULT_BACKEND = env("REDIS_URL")
CACHEOPS_REDIS = env("CACHE_URL")

...
``` 

since code used `setdefault` it will ignore to update that in `django-environ/environ/environ.py`
```py
# line 654
cls.ENVIRON.setdefault(key, str(val))
```

### PR DESCRIPTION
**Pull request by SmileyChris**
Fixes #249

### CODE REVIEW

**Comment by sergeyklay** [comment]
@SmileyChris Could you please send this path to `develop` branch?

**Comment by SmileyChris** [comment]
Updated against develop

coveralls check is a bit silly, since I simplified a file by a line, it dropped average coverage

**Review by sergeyklay — APPROVED** [review]
Looks good to me

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
