### PR TITLE
Allow proxied vals in dotenv

### PR DESCRIPTION
**Pull request by j00bar**

### CODE REVIEW

**Comment by theskumar** [comment]
Trying to understand, what are proxied values? Is there a reason, it needs to handled implicitly? 

A documentation along the PR will help too.

**Comment by j00bar** [comment]
c.f. https://github.com/joke2k/django-environ/blob/201bacd3fb6ea263f6c92b84afc8f9395755b913/environ/environ.py#L257-260

Under the current code, if `env` is an `Env()` object, and you call `env('FOO')`, and `FOO` is defined in the environment as `$BAR`, then `env('FOO')` will return the value of `os.environ['BAR']`. I'm porting the same functionality over to `Env.read_env()` to allow your `.env` file var/value to reference other environment variables - that's all.

My use case is that I'm using Memcachier on Heroku. Because that requires authenticated memcache access, I can't use the stock pylibmc backend, so I'm using https://github.com/django-pylibmc/django-pylibmc/ instead - which allows configuration of the memcached location, username, and password from environment variables. Heroku provides `MEMCACHER_SERVERS`, `MEMCACHER_USERNAME`, and `MEMCACHER_PASSWORD`, bur django-pylibmc requires `MEMCACHE_SERVERS`, `MEMCACHE_USERNAME`, and `MEMCACHE_PASSWORD`. My `.env` file has lines like `MEMCACHE_USERNAME=$MEMCACHIER_USERNAME` - I'd like that to actually work.

HTH.

**Comment by theskumar** [comment]
> My .env file has lines like MEMCACHE_USERNAME=$MEMCACHIER_USERNAME - I'd like that to actually work.

This is interesting and useful too. Thanks for taking time to explain.

**Comment by theskumar** [comment]
I search through the docs and it seems are no existing doc about the proxied values. It will be very useful to have changes well documented as part of the PR.

**Comment by joke2k** [comment]
Hi, this functionality is already implemented, but not documented ^__^

See https://github.com/joke2k/django-environ/blob/develop/environ/environ.py#L259

**Pull request closed without merging**
