### PR TITLE
Added secure redis backend and Django 1.11 db config

### PR DESCRIPTION
**Pull request by mjrimrie**

### CODE REVIEW

**Comment by gnagel** [comment]
Nice!  This is exactly what I need to support Redis with SSL 👍

**Comment by mjrimrie** [comment]
Glad it helps!

**Comment by gnagel** [comment]
Hi @joke2k!
Can you merge this update in?  I'd love to use this in the next release of `django-environ` 
Thanks!

**Comment by cdobbyn** [comment]
@joke2k - What is required to merge this in? This is necessary for anyone using secure redis i.e. Amazon Elasticache.

**Pull request merged**
