### PR TITLE
Make inline comments handling optional and disabled by default

### LINKED ISSUE #499: Hash sign inside double quotes is interpreted as the start of a comment
Ran into this problem when updating to `0.11.2` for a project with an `.env` file like this:

```
SECRET_KEY="abc#def"
```

The `SECRET_KEY` used to be `abc#def` but now is read as `"abc`.

Apparently the `#` is interpreted as the start of a comment now, except in *singly*-quoted strings.
Looking at the tests for this new feature only the single-quoted case is tested, but the documentation contains examples with double quotes. It seems they are not treated the same in this case; is this intended behaviour?

### PR DESCRIPTION
**Pull request by sergeyklay**
Disabled inline comments handling (that was introduced in #475) by default due to potential side effects. While the feature itself is useful, the project's philosophy dictates that it should not be enabled by default for all users.

Closes #499

### CODE REVIEW

**Comment by lvanderree** [comment]
:+1:  this is exactly what I had in mind after hearing about the issues: Add a feature flag to enable/disable it

**Review by painassasin — APPROVED** [review]

**Comment by ognjenk** [comment]
Do you maybe know when this fix might be pushed into release?

**Comment by sergeyklay** [comment]
> Do you maybe know when this fix might be pushed into release?

We'll try to release next week.

**Comment by simonkern** [comment]
Sorry for bringing this issue up again, but any update on when this will be released? I've yet encountered another instance of `corrupted session data` because the `SECRET_KEY` was interpreted differently for uWSGI and gunicorn / uvicorn.

**Comment by jiayouzl** [comment]
> > Do you maybe know when this fix might be pushed into release?
> 
> We'll try to release next week.

Has the new version not been released yet? I have also encountered this problem.

**Comment by jiayouzl** [comment]
> > Do you maybe know when this fix might be pushed into release?
> 
> We'll try to release next week.

Has the new version not been released yet? I have also encountered this problem.

I found that this issue only occurs in Ubuntu. The "#" symbol in the .env file is not affected on macOS system. What's going on?

**Comment by dklotz** [comment]
> We'll try to release next week.

@sergeyklay Sorry to sound a bit pushy, but any updates on when this release will happen? This seems to affect a lot of people (cf #519), especially with `SECRET_KEY` and the related session data corruption.

**Comment by jiayouzl** [comment]
> > We'll try to release next week.
> 
> @sergeyklay Sorry to sound a bit pushy, but any updates on when this release will happen? This seems to affect a lot of people (cf #519), especially with `SECRET_KEY` and the related session data corruption.

I have been waiting for a long time too. In fact, they have already fixed it in the branch but just haven't released it. 😀

**Comment by dklotz** [comment]
> I have been waiting for a long time too. In fact, they have already fixed it in the branch but just haven't released it. 😀

Yes, I also noticed that. For us the workaround for now is just using the version from the git `develop` branch in our `pyproject.toml`:
```
[tool.poetry.dependencies]
...
django-environ = { git = "https://github.com/joke2k/django-environ.git", rev = "a1113e41" } # TODO: switch to release once this bug is fixed: https://github.com/joke2k/django-environ/issues/519
```

**Pull request merged**
