### PR TITLE
Percent-decode url parts

### PR DESCRIPTION
**Pull request by joke2k**
Code to handle percent-encoded urls.
Includes #48 (username and password decoding) and decodes path and query too.

### CODE REVIEW

**Comment by anthonysutardja** [comment]
Bump -- would love to see this in the next release

**Comment by gipi** [comment]
+1

**Comment by ntravis** [comment]
@joke2k Any reason this hasn't been merged in? It would resolve our divergent fork due to handling special characters in passwords.

**Comment by urkh** [comment]
this issue still continue

**Comment by mrinalsinha** [comment]
My password contains '?' in it and it is breaking the db url.
any suggestions on how to fix it?

`  File "/home/mrinal/projects/corpdata/venv/lib/python3.5/site-packages/environ/environ.py", line 402, in db_url_config
    'PORT': _cast_int(url.port) or '',
  File "/usr/lib/python3.5/urllib/parse.py", line 158, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: "'raNPh7bf"`

**Comment by gipi** [comment]
@mrinalsinha this is not stackoverflow

**Pull request merged**
