### PR TITLE
Add support for Django CockroachDB driver

### PR DESCRIPTION
**Pull request by stevewilliamsuk**
As per https://github.com/joke2k/django-environ/issues/509 adds support for Django CockroachDB

### CODE REVIEW

**Comment by stevewilliamsuk** [comment]
@joke2k could you please help us out with some feedback on this PR?

**Comment by stevewilliamsuk** [comment]
@sergeyklay are you able to help us out with some feedback/approval on this PR?

**Comment by pataquets** [comment]
Tip: those wanting to try the PR real quick "straight-from-this-PR", just add this line to your dependencies (ie. `requirements.txt`):
```
git+https://github.com/joke2k/django-environ@refs/pull/511/head
```

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thank you for contributing! And I'm sorry for the delay.

**Pull request merged**
