### PR TITLE
adding rfind and find methods to Path

### PR DESCRIPTION
**Pull request by burhan**
I have added two methods to support `rfind()` and `find()` to provide compatibility for those django applications that depend on settings but are not "Path" aware.

I ran into this issue with [`django-encrypted-fields`](https://github.com/defrex/django-encrypted-fields):
```
File "/home/burhan/work/projects/aubkw/esch/pgw/models.py", line 11, in Gateway
    username = EncryptedCharField(max_length=200)
File "/home/burhan/work/envs/esch-2.7/local/lib/python2.7/site-packages/encrypted_fields/fields.py", line 121, in __init__
    self.keyname = os.path.dirname(self.keydir)
File "/home/burhan/work/envs/esch-2.7/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'Path' object has no attribute 'rfind'
```

### CODE REVIEW

**Comment by burhan** [comment]
Also did some PEP8 formatting (which is why there are a few whitespace changes).

**Comment by ei-grad** [comment]
Such a good feature, but can't add it to my repository because of your formatting changes :-(

**Comment by joke2k** [comment]
Hi @burhan can you redo a PR without pep8 fixes?
its really hard to merge.
Thank you

**Comment by joke2k** [comment]
Never mind, I did it

**Pull request merged**
